version: "3"
services:
    api:
        image: ghcr.io/yumis-coconudge/zempie-server:${TAG}
        env_file:
            - .env
        ports:
            - 5000:5000
        volumes:
            - ./upload:/app/upload
